### ISSUE TITLE
NifStruct doesn't work if the module attribute is not the first attribute on the struct. 

### ISSUE THREAD

**Issue by kraythen** [hansihe/rustler#152]
If you change `rustler_tests/src/test_codegen.rs` to add any other attribute to the struct and the `module` isn't the first attribute than the macro will reflect a compile error: 

```rust
#[derive(Debug, NifStruct)]
#[must_use]
#[module = "AddStruct"]
struct AddStruct {
    lhs: i32,
    rhs: i32,
}
``` 

```
13:17:59 ➜  ~/dev/rustler/rustler_tests ➜  git:(master) ✗ mix test
Compiling NIF crate :rustler_test (.)...
   Compiling rustler_test v0.1.0 (file:///Users/rsimmons/dev/rustler/rustler_tests)
error: proc-macro derive panicked
  --> rustler_tests/src/test_codegen.rs:37:17
   |
37 | #[derive(Debug, NifStruct)]
   |                 ^^^^^^^^^
   |
   = help: message: NifStruct requires a 'module' attribute

error: aborting due to previous error

error: Could not compile `rustler_test`.

To learn more, run the command again with --verbose.
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:60: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:34: Mix.Tasks.Compile.All.with_logger_app/1
```

I think this is related to the code in the macro in `ex_struct.rs`that is defined as: 
```rust
    let elixir_module = {
        let ref attr_value = ast.attrs.first().expect("NifStruct requires a 'module' attribute").value;
        assert!(attr_value.name() == "module", "NifStruct requires a 'module' attribute");
        match *attr_value {
            MetaItem::NameValue(_, Lit::Str(ref value, _)) => format!("Elixir.{}", value),
            _ => panic!("NifStruct requires a 'module' attribute"),
        }
    };
```

If any attribute supersedes the module attribute the code fails. I will work on seeing if I can make a fix.

**Comment by kraythen** [comment]
Any chance of getting a crate pushed ?
