### ISSUE TITLE
Failing Travis CI

### ISSUE THREAD

**Issue by korczis** [hansihe/Rustler#25]
It seems build is failing on [Travis CI](https://travis-ci.org/hansihe/Rustler/builds/164501625)

```
running 2 tests
test NifTerm<'a>::decode_0 ... ignored
test list::NifListIterator_0 ... FAILED
failures:
---- list::NifListIterator_0 stdout ----
	error[E0412]: type name `NifListIterator` is undefined or not in scope
 --> <anon>:2:24
  |
2 |     let list_iterator: NifListIterator = try!(list_term.decode());
  |                        ^^^^^^^^^^^^^^^ undefined or not in scope
  |
  = help: no candidates by the name of `NifListIterator` found in your project; maybe you misspelled the name or forgot to import an external crate?
error[E0425]: unresolved name `list_term`
 --> <anon>:2:47
  |
2 |     let list_iterator: NifListIterator = try!(list_term.decode());
  |                                               ^^^^^^^^^ unresolved name
error[E0412]: type name `NifResult` is undefined or not in scope
 --> <anon>:4:13
  |
4 | let result: NifResult<Vec<i64>> = iter
  |             ^^^^^^^^^^^^^^^^^^^ undefined or not in scope
  |
  = help: no candidates by the name of `NifResult` found in your project; maybe you misspelled the name or forgot to import an external crate?
error[E0425]: unresolved name `iter`
 --> <anon>:4:35
  |
4 | let result: NifResult<Vec<i64>> = iter
  |                                   ^^^^ unresolved name
error[E0412]: type name `NifResult` is undefined or not in scope
 --> <anon>:9:16
  |
9 |     .collect::<NifResult<Vec<i64>>>();
  |                ^^^^^^^^^^^^^^^^^^^ undefined or not in scope
  |
  = help: no candidates by the name of `NifResult` found in your project; maybe you misspelled the name or forgot to import an external crate?
error[E0308]: mismatched types
 --> <anon>:2:42
  |
2 |     let list_iterator: NifListIterator = try!(list_term.decode());
  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
  |
  = note: expected type `()`
  = note:    found type `std::result::Result<_, _>`
  = note: this error originates in a macro outside of the current crate
error: aborting due to previous error(s)
thread 'list::NifListIterator_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:185
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    list::NifListIterator_0
test result: FAILED. 0 passed; 1 failed; 1 ignored; 0 measured
error: test failed
The command "cargo test --verbose" exited with 101.
Done. Your build exited with 1.
```

**Comment by hansihe** [comment]
Fixed the issue.

**Comment by korczis** [comment]
```

    Finished release [optimized] target(s) in 216.46 secs
Generated rustler_test app
...thread '<unnamed>' panicked at 'list iterator found improper list', /home/travis/build/hansihe/Rustler/src/list.rs:74
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by hansihe** [comment]
The test suite does failure tests. This is normal.
